/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffd4c5",
        "surface-container-highest": "#e2e1ed",
        "on-surface-variant": "#434654",
        "surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#802a00",
        "error": "#ba1a1a",
        "secondary": "#735c00",
        "tertiary": "#852b00",
        "tertiary-fixed-dim": "#ffb59a",
        "outline": "#737686",
        "secondary-fixed": "#ffe083",
        "on-background": "#191b23",
        "primary-fixed-dim": "#b5c4ff",
        "surface-container": "#ededf8",
        "inverse-surface": "#2e3039",
        "surface-dim": "#d9d9e4",
        "on-primary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3fe",
        "background": "#faf8ff",
        "on-primary-container": "#d4dcff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#eec200",
        "primary": "#003fb1",
        "on-primary-fixed-variant": "#003dab",
        "on-secondary-fixed": "#231b00",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f0f0fb",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#574500",
        "on-secondary": "#ffffff",
        "surface-tint": "#1353d8",
        "surface-bright": "#faf8ff",
        "tertiary-fixed": "#ffdbcf",
        "outline-variant": "#c3c5d7",
        "on-secondary-container": "#6f5900",
        "on-tertiary-fixed": "#380d00",
        "on-primary-fixed": "#00174d",
        "on-error": "#ffffff",
        "tertiary-container": "#ad3b00",
        "secondary-container": "#fed01b",
        "surface-variant": "#e2e1ed",
        "primary-container": "#1a56db",
        "surface-container-high": "#e7e7f3",
        "inverse-primary": "#b5c4ff",
        "on-surface": "#191b23",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "lg": "24px",
        "xl": "40px",
        "base": "4px",
        "container-margin": "16px",
        "xs": "4px",
        "sm": "8px",
        "gutter": "12px",
        "md": "16px",
      },
      fontFamily: {
        "h2": ["Lexend"],
        "button": ["Inter"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "display": ["Lexend"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "h1": ["Lexend"],
      },
      fontSize: {
        "h2": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "button": ["16px", { "lineHeight": "20px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "h1": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
      },
    },
  },
  plugins: [],
}